[project]
name = "python"
version = "0.1.0"
description = "My portfolio website"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=5.2.7",
]

[dependency-groups]
prod = [
    "gunicorn>=23.0.0",
]

[tool.ruff]
line-length = 80
